import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Thread Affair</title>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="icon" href="/favicon.ico"></link>
      </Head>
      <div>
        Hello
        <i className="fa-solid fa-cart-arrow-down"></i>
      </div>

      <div className="mt-4">
      </div>
    </div>
  );
}
